[features]
seeds = false
skip-lint = false
[programs.localnet]
my_first_pyth_app = "56o3NWoUrmEz4jrkrxXnTcUem7PYNwes9trxPGMfc2yR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/gbescos/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
